/* Page-side measurements; native actions are dispatched by forge-ui.cjs.
 * Measurement/assertion functions never scroll or focus a control.
 */
window.forgeUi=(()=>{
 const b=window.__lumenfallQaBridge,q=s=>document.querySelector(s),copy=x=>JSON.parse(JSON.stringify(x));let tickStart;
 function ok(v,m){if(!v)throw Error(m);}
 function state(){return b.getState();}
 function setup(inset){b.resetFeedback();let s=b.freshStateSnapshot();s.maxDepthEver=101;s.depth=101;s.enemyDepth=101;s.enemyMaxHp=b.enemyHpFor(101);s.enemyHp=s.enemyMaxHp;s.lumen=0;s.shards=0;s.questDay=b.currentDay();s.loginStreak=1;b.setState(s);b.renderLayout();q('[data-tab="forge"]').click();document.documentElement.style.setProperty('--safe-top',inset+'px');document.documentElement.style.setProperty('--safe-bottom',inset+'px');tickStart=state();if(new URLSearchParams(location.search).get('qaScenario')==='self-test-forge-ui-handler')q('[data-queue="luminoustracking"]').addEventListener('click',function(){b.save();});ok(!b.getFlags().reloadInProgress,'production tick/save flags remain enabled');}
 function prepare(selector,focus){const el=q(selector);if(focus)el.focus({preventScroll:true});el.scrollIntoView({block:'center'});}
 function measure(selector){const el=q(selector),r=el.getBoundingClientRect(),m=q('main'),v=m.getBoundingClientRect(),nav=q('nav.tabbar').getBoundingClientRect(),top=Math.max(v.top,0),bottom=Math.min(v.bottom,nav.top,innerHeight),x=r.x+r.width/2,y=r.y+r.height/2;return {scrollTop:m.scrollTop,area:{top,bottom},rect:{left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height},x,y,visible:r.top>=top&&r.bottom<=bottom&&r.left>=v.left&&r.right<=v.right,hit:el.contains(document.elementFromPoint(x,y)),focus:document.activeElement.matches('[data-queue],[data-research],[data-mult]')?{queue:document.activeElement.dataset.queue,research:document.activeElement.dataset.research,mult:document.activeElement.dataset.mult}:null,queue:state().researchQueue.luminoustracking};}
 function visible(r,label){ok(r.visible&&r.hit,label+' visible and hittable: '+JSON.stringify(r));}
 function checkBulk(){const entries=[...document.querySelectorAll('#tab-forge [data-mult]')].map(el=>({id:el.dataset.mult,...measure('[data-mult="'+el.dataset.mult+'"]')}));ok(entries.length===7,'seven real bulk controls');entries.forEach(r=>{ok(r.rect.width>=44&&r.rect.height>=44,'bulk minimum 44x44: '+JSON.stringify(r));visible(r,'bulk '+r.id);});entries.forEach((a,i)=>entries.slice(i+1).forEach(c=>ok(Math.min(a.rect.right,c.rect.right)<=Math.max(a.rect.left,c.rect.left)||Math.min(a.rect.bottom,c.rect.bottom)<=Math.max(a.rect.top,c.rect.top),'bulk hit rectangles do not overlap')));ok(q('#tab-forge').scrollWidth<=q('#tab-forge').clientWidth,'no Forge horizontal overflow');return entries;}
 function stableEconomy(a,c){for(const k of ['research','spirits','nodes','longStudyLevels','activeStudies','formationRebuild','lumen','shards','motes','prisms','comets','sigils','totalKills','ascendCount','dailyStats'])ok(JSON.stringify(a[k])===JSON.stringify(c[k]),'Queue/render changes no economy '+k);}
 function checkQueue(before,start,on,keyboard){const r=measure('[data-queue="luminoustracking"]'),s=state();visible(r,'last Queue after action');ok(r.scrollTop===before.scrollTop,'unchanged Queue geometry preserves scrollTop '+JSON.stringify({before:before,after:r}));ok(r.queue===on,'exactly one Queue toggle');if(keyboard)ok(r.focus?.queue==='luminoustracking','same logical keyboard focus');else ok(!document.activeElement.matches(':focus-visible'),'touch does not introduce keyboard focus indicator');stableEconomy(s,start);const expected=copy(start.researchQueue);expected.luminoustracking=on;ok(JSON.stringify(s.researchQueue)===JSON.stringify(expected),'only intended Queue choice changed');const saved=JSON.parse(b.rawSave());ok(saved.researchQueue.luminoustracking===on,'existing saveflow persists choice');ok(!document.documentElement.hasAttribute('data-qa-runtime-error'),'no runtime errors');return {...r,gameplay:{lumen:s.lumen,shards:s.shards,research:s.research,enemyHp:s.enemyHp,heroResource:s.heroResource,totalKills:s.totalKills}};}
 function actionBefore(){ok(window.__qaForgeStartup.completed,'startup callback/save complete before measurement');window.__qaForgeAction={id:'luminoustracking',handlers:0,saves:0};return {state:state(),saves:b.lifecycleTrace().filter(e=>e.type==='save').length};}
 function checkAction(before){const s=state(),expected=copy(before.state),action=window.__qaForgeAction,after=b.lifecycleTrace().filter(e=>e.type==='save').length;expected.researchQueue.luminoustracking=!expected.researchQueue.luminoustracking;ok(JSON.stringify(s)===JSON.stringify(expected),'immediate controlled-time state changes only intended Queue');const counts={before:before.saves,after,handlers:action.handlers,handlerSaves:action.saves};ok(action.handlers===1&&action.saves===1&&after===before.saves+1,'exactly one Queue handler and associated save: '+JSON.stringify(counts));window.__qaForgeAction=null;return counts;}

 function checkTicks(){const s=state();ok(s.enemyHp<tickStart.enemyHp,'subsequent production ticks really advance combat');return {beforeHp:tickStart.enemyHp,afterHp:s.enemyHp,flags:b.getFlags()};}
 function preparePurchase(level){let s=state(),cost=b.forge.cost('luminoustracking',level,1);s.research.luminoustracking=level;s.lumen=level===8?cost.lumen:1e12;s.shards=level===8?cost.shard:1e12;s.researchQueue.luminoustracking=false;b.setState(s);b.renderLayout();prepare('[data-research="luminoustracking"]',true);}
 function purchaseBefore(){return {state:state(),preview:b.forge.preview('luminoustracking',1),control:measure('[data-research="luminoustracking"]')};}
 function checkPurchase(before){const s=state(),p=before.preview.plan;ok(p.buyCount===1&&s.research.luminoustracking===before.state.research.luminoustracking+1,'real purchase exactly one level');ok(s.lumen===before.state.lumen-p.cost.lumen&&s.shards===before.state.shards-p.cost.shard,'single exact debit');ok(s.dailyStats.research===(before.state.dailyStats.research||0)+1,'counter increments once');ok(q('[data-research="luminoustracking"]').disabled,'cap or exhausted budget disables purchase');const r=measure('[data-queue="luminoustracking"]');visible(r,'cap fallback Queue');ok(r.focus?.queue==='luminoustracking','cap fallback stays on same upgrade');ok(q('[data-forge-card="luminoustracking"]').textContent.includes(s.research.luminoustracking===10?'Next: Maxed':'No purchase (0 levels)'),'cap/unaffordable preview current');return {control:r,lumen:s.lumen,shards:s.shards,level:s.research.luminoustracking};}
 function checkBulkChoice(value){const r=measure('[data-mult="'+value+'"]');visible(r,'selected bulk');ok(r.focus?.mult===value&&q('[data-mult="'+value+'"]').getAttribute('aria-pressed')==='true','selected bulk focus and state');const node=b.forge.nodes().find(n=>n.id==='arcanecal'),model=b.forge.preview(node.id,value==='max'?'max':Number(value));ok(q('[data-forge-card="arcanecal"]').textContent.includes('Purchase impact: '+model.plan.buyCount+' level(s)'),'authoritative bulk preview');return {value,control:r,count:model.plan.buyCount};}
 function affordability(){let s=state();s.lumen=0;s.shards=0;s.maxDepthEver=11;s.depth=11;s.enemyDepth=11;s.enemyMaxHp=b.enemyHpFor(11);s.enemyHp=s.enemyMaxHp;b.setState(s);b.renderLayout();prepare('[data-queue="arcanecal"]',true);const before=state();b.renderLayout();ok(JSON.stringify(state())===JSON.stringify(before),'render pure at controlled time');b.refreshAffordability();}
 function checkAffordability(){const r=measure('[data-queue="arcanecal"]');visible(r,'locked Queue after live frames');ok(r.focus?.queue==='arcanecal','locked Queue retains focus');ok(q('[data-research="arcanecal"]').disabled&&q('[data-forge-card="arcanecal"]').textContent.includes('Reach Rift 12'),'locked exact requirement');ok(q('[data-research="focus"]').disabled,'legacy affordability refreshed');return r;}
 function checkRift(){const m=q('main');ok(m.classList.contains('rift-scroll-locked')&&m.scrollTop===0&&m.scrollHeight<=m.clientHeight+1,'compact scroll-free Rift return');ok(!document.documentElement.hasAttribute('data-qa-runtime-error'),'no runtime errors');return {scrollTop:m.scrollTop,height:m.clientHeight,content:m.scrollHeight};}
 return {setup,prepare,measure,state,actionBefore,checkAction,checkBulk,checkQueue,checkTicks,preparePurchase,purchaseBefore,checkPurchase,checkBulkChoice,affordability,checkAffordability,checkRift};
})();
