/* Native CDP touch/keyboard at mobile widths; production page remains unmodified. */
const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const [chrome,url,scenario]=process.argv.slice(2),profile=fs.mkdtempSync(path.join(os.tmpdir(),'lumenfall-lab-motes-'));
const browser=spawn(process.env.LUMENFALL_QA_CDP_CHROME||chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--remote-debugging-pipe','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe','pipe','pipe']});
let seq=0,buffer='',stderr='',session,closed=false;const pending=new Map(),records=[];
function rejectPending(message){for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error(message+' '+p.method));}pending.clear();}
const completion=new Promise(resolve=>{browser.once('error',e=>{rejectPending(e.message);resolve({error:e.message});});browser.once('close',(code,signal)=>{closed=true;rejectPending('browser closed');resolve({code,signal});});});
browser.stderr.on('data',b=>{stderr=(stderr+b).slice(-4000);});
for(const stream of [browser.stdio[3],browser.stdio[4]])stream.on('error',e=>rejectPending(e.message));
browser.stdio[4].on('data',b=>{buffer+=b;let end;while((end=buffer.indexOf('\0'))!==-1){const raw=buffer.slice(0,end);buffer=buffer.slice(end+1);if(!raw)continue;const m=JSON.parse(raw);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}}});
function send(method,params={},sid=session){return new Promise((resolve,reject)=>{const id=++seq,timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout '+method+' '+stderr));},15000);pending.set(id,{resolve,reject,timer,method});browser.stdio[3].write(JSON.stringify({id,method,params,...(sid?{sessionId:sid}:{})})+'\0');});}
async function evaluate(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
function assert(v,m){if(!v)throw Error(m);}
async function key(key){const spec=key==='Space'?{key:' ',code:'Space',windowsVirtualKeyCode:32}:{key,code:key,windowsVirtualKeyCode:{ArrowDown:40,ArrowUp:38,Tab:9,Enter:13,Escape:27}[key]};await send('Input.dispatchKeyEvent',{type:key==='Enter'?'keyDown':'rawKeyDown',...(key==='Enter'?{text:'\r',unmodifiedText:'\r'}:{}),...spec});await send('Input.dispatchKeyEvent',{type:'keyUp',...spec});}
async function snapshot(){return evaluate(`(()=>{const b=window.__lumenfallQaBridge,s=document.querySelector('[data-study-speed-target="guardmastery"]'),u=document.querySelector('[data-study-use-motes="guardmastery"]'),a=b.getState(),r=s.getBoundingClientRect();return {state:a,primary:b.rawSave(),recovery:b.rawRecovery(),events:b.lifecycleTrace(),value:s.value,focused:Object.assign({},document.activeElement?.dataset),pressed:u.getAttribute('aria-pressed'),speed:a.activeStudies.find(e=>e.id==='guardmastery').speedMult,rect:{x:r.x,y:r.y,width:r.width,height:r.height},scroll:document.querySelector('main').scrollTop,fit:document.documentElement.scrollWidth<=innerWidth&&document.querySelector('#study-list').scrollWidth<=document.querySelector('#study-list').clientWidth+1,errors:window.__lumenfallQaContext.errors};})()`);}
async function run(){
 const motion=scenario.includes('reduced')?'reduce':'no-preference';
 for(const width of [320,390,430]) for(const textScale of [1,2]){
  const context=await send('Target.createBrowserContext',{},null),tab=await send('Target.createTarget',{url:'about:blank',browserContextId:context.browserContextId},null);session=(await send('Target.attachToTarget',{targetId:tab.targetId,flatten:true},null)).sessionId;
  await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});await send('Emulation.setTouchEmulationEnabled',{enabled:true});await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:motion}]});await send('Page.enable');await send('Page.navigate',{url});
  for(let i=0;i<150&&!await evaluate('!!window.__labMotesNativeReady');i++)await new Promise(r=>setTimeout(r,20));
  assert(await evaluate('!!window.__labMotesNativeReady'),'native Lab page ready');await evaluate('window.__qaForgeStartup.promise');await evaluate('document.fonts.ready.then(()=>true)');
  await evaluate(`document.documentElement.style.fontSize='${textScale*16}px';window.__lumenfallQaBridge.uiMeasurementPause(true)`);
  const labUi=await evaluate('runLabUiQa(window.__lumenfallQaBridge,window.__lumenfallQaContext,function(v,m){if(!v)throw Error(m);})');
  const collapsedAx=await send('Accessibility.getFullAXTree');
  assert(!collapsedAx.nodes.some(n=>!n.ignored&&/Queued speed|Queue speed up|Close speed up/.test(n.name?.value||'')),'closed panels absent from accessibility tree');
  await evaluate('document.querySelector("[data-running-study=guardmastery]").scrollIntoView({block:"start"})');
  await new Promise(r=>setTimeout(r,250));
  if(process.env.LUMENFALL_QA_EVIDENCE_DIR){const shot=await send('Page.captureScreenshot',{format:'png'});fs.mkdirSync(process.env.LUMENFALL_QA_EVIDENCE_DIR,{recursive:true});fs.writeFileSync(path.join(process.env.LUMENFALL_QA_EVIDENCE_DIR,'lab-ui-card-'+width+'-'+motion+'-text'+textScale+'.png'),Buffer.from(shot.data,'base64'));}
  await evaluate(`(()=>{const b=window.__lumenfallQaBridge;b.uiMeasurementPause(true);b.resetFeedback();const s=labMotesSeed(b,window.__lumenfallQaContext);s.motes=0;s.studySpeedTargets.guardmastery=2;s.activeStudies=[{id:'guardmastery',remainingSec:150,totalDurationSec:150,speedMult:1}];s.enemyHp=s.enemyMaxHp=1e9;b.setState(s);b.save();b.renderLayout();document.querySelector('[data-tab="research"]').click();document.querySelector('[data-study-details="guardmastery"]').click();document.querySelector('[data-study-speed-target="guardmastery"]').scrollIntoView({block:'center'});})()`);
  await evaluate('document.querySelector("[data-study-speed-close=guardmastery]").focus()');await key('Enter');
  assert(await evaluate('document.activeElement.dataset.studyDetails')==='guardmastery','native Close returns focus '+JSON.stringify(await evaluate('({focus:document.activeElement.outerHTML,panelHidden:document.querySelector("[data-study-inspection=guardmastery]").hidden})')));
  await key('Space');assert(await evaluate('document.activeElement.dataset.studyDetails')==='guardmastery','native Space opens panel and retains visible opener focus');
  await key('Tab');assert(await evaluate('document.activeElement.dataset.studyUseMotes')==='guardmastery','native Tab skips unavailable tiers and reaches queue switch');
  await key('Tab');assert(await evaluate('document.activeElement.dataset.studySpeedTarget')==='guardmastery','native Tab reaches tier selection');
  await key('Tab');assert(await evaluate('document.activeElement.dataset.studySpeedClose')==='guardmastery','native Tab reaches Close');
  await key('Escape');assert(await evaluate('document.activeElement.dataset.studyDetails')==='guardmastery','native Escape closes panel and returns focus');
  await key('Enter');
  const expandedAx=await send('Accessibility.getFullAXTree');
  assert(expandedAx.nodes.some(n=>!n.ignored&&n.role?.value==='region'&&/Guardian.*Speed up/.test(n.name?.value||'')),'expanded panel is a named region');
  assert(expandedAx.nodes.some(n=>!n.ignored&&n.role?.value==='progressbar'&&/Guardian/.test(n.name?.value||'')),'progressbar exposed to accessibility tree');
  await evaluate('document.querySelector("[data-study-speed-target=guardmastery]").scrollIntoView({block:"center"})');
  await new Promise(r=>setTimeout(r,350));let before=await snapshot();assert(before.fit&&before.rect.height>=44,'mobile select fits '+width+' '+JSON.stringify(before.rect));
  await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:before.rect.x+before.rect.width/2,y:before.rect.y+before.rect.height/2}]});await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await key('Escape');
  let touched=await snapshot();const hit=await evaluate(`(()=>{const r=document.querySelector('[data-study-speed-target=guardmastery]').getBoundingClientRect(),e=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {tag:e?.tagName,html:e?.outerHTML.slice(0,300),intro:document.querySelector('#startup-intro').className};})()`);assert(touched.focused.studySpeedTarget==='guardmastery'&&touched.value==='2','native touch focus without changing choice '+JSON.stringify({rect:before.rect,focused:touched.focused,value:touched.value,hit}));
  await key('ArrowDown');let selected=await snapshot();assert(selected.value==='3'&&selected.state.studySpeedTargets.guardmastery===3&&selected.focused.studySpeedTarget==='guardmastery','real keyboard selects3x without money');assert(selected.events.length===touched.events.length+1&&selected.state.motes===0&&selected.speed===1&&!selected.state.studyUseMotes.guardmastery,'one save, no payment or activation');
  await evaluate('document.querySelector("[data-study-use-motes=guardmastery]").focus({preventScroll:true})');before=await snapshot();await key('Space');let on=await snapshot();assert(on.pressed==='true'&&on.state.studyUseMotes.guardmastery&&!on.state.studyQueue.guardmastery&&on.speed===1,'native Space ON retains pending target, queue independent');assert(on.focused.studyUseMotes==='guardmastery'&&on.events.length===before.events.length+1,'ON focus and one handler/save');
  before=await snapshot();await evaluate('window.__lumenfallQaBridge.renderLayout();window.__lumenfallQaBridge.refreshAffordability()');let rendered=await snapshot();assert(JSON.stringify([rendered.state,rendered.primary,rendered.recovery,rendered.events])===JSON.stringify([before.state,before.primary,before.recovery,before.events]),'render/affordability purity');assert(rendered.focused.studyUseMotes==='guardmastery','render focus retained');
  await evaluate('window.__lumenfallQaBridge.uiMeasurementPause(false)');await new Promise(r=>setTimeout(r,350));await evaluate('window.__lumenfallQaBridge.uiMeasurementPause(true)');let waiting=await snapshot();assert(waiting.state.activeStudies[0].remainingSec<rendered.state.activeStudies[0].remainingSec&&waiting.speed===1&&waiting.state.motes===0&&waiting.state.studySpeedTargets.guardmastery===3,'real ticks wait1x at zero budget');
  await evaluate(`(()=>{const b=window.__lumenfallQaBridge,s=b.getState();s.motes=60;b.setState(s);b.renderLayout();document.querySelector('[data-study-speed-target="guardmastery"]').focus({preventScroll:true});b.uiMeasurementPause(false);})()`);await new Promise(r=>setTimeout(r,350));await evaluate('window.__lumenfallQaBridge.uiMeasurementPause(true)');let bought=await snapshot();assert(bought.speed===3&&bought.state.motes===0&&bought.focused.studySpeedTarget==='guardmastery'&&bought.value==='3','authoritative live purchase reflects paid3x, exact60, focus/intent retained');assert(JSON.parse(bought.primary).activeStudies[0].speedMult===3&&bought.primary===bought.recovery,'automatic purchase persisted through normal save/recovery');
  await evaluate('document.querySelector("[data-study-use-motes=guardmastery]").focus({preventScroll:true})');await key('Space');let off=await snapshot();assert(off.pressed==='false'&&!off.state.studyUseMotes.guardmastery&&off.speed===3&&off.focused.studyUseMotes==='guardmastery','native OFF preserves paid speed and focus');
  await evaluate('document.querySelector("[data-study-speed-target=guardmastery]").focus({preventScroll:true})');await key('ArrowUp');let lower=await snapshot();assert(lower.value==='2'&&lower.state.studySpeedTargets.guardmastery===2&&lower.speed===3,'lower native target never downgrades paid speed');
  const controls=await evaluate(`Array.from(document.querySelectorAll('[data-study-use-motes],[data-study-speed-target]')).filter(e=>e.getClientRects().length).map(e=>{const r=e.getBoundingClientRect();return {w:r.width,h:r.height,label:e.getAttribute('aria-label')};})`);assert(controls.every(r=>r.w>=44&&r.h>=44&&r.label),'all new controls44px and named');assert(lower.fit&&!lower.errors.length,'no overflow/runtime errors');
  await evaluate('document.querySelector("[data-study-speed-target=guardmastery]").scrollIntoView({block:"center"});document.activeElement.blur()');
  if(process.env.LUMENFALL_QA_EVIDENCE_DIR){const shot=await send('Page.captureScreenshot',{format:'png'});fs.mkdirSync(process.env.LUMENFALL_QA_EVIDENCE_DIR,{recursive:true});fs.writeFileSync(path.join(process.env.LUMENFALL_QA_EVIDENCE_DIR,'lab-motes-'+width+'-'+motion+'-text'+textScale+'.png'),Buffer.from(shot.data,'base64'));}
  records.push({width,motion,textScale,labUi,selected,on,waiting,bought,off,lower,controls});await send('Target.disposeBrowserContext',{browserContextId:context.browserContextId},null);
 }
 return {status:'pass',scenario,records};
}
(async()=>{let result;try{result=await run();}catch(error){result={status:'fail',scenario,message:error.message,records};}
 try{assert(pending.size===0,'all CDP operations settled');if(!closed)await send('Browser.close',{},null).catch(()=>{});let timer;const done=await Promise.race([completion,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('browser close timeout')),5000);})]).finally(()=>clearTimeout(timer));assert(closed&&done.code===0&&!done.error,'graceful browser termination');await fs.promises.rm(profile,{recursive:true,force:true,maxRetries:3,retryDelay:100});result.teardown={browser:done,pending:pending.size,profileRemoved:!fs.existsSync(profile)};}catch(error){browser.kill('SIGKILL');result.status='fail';result.teardown={message:error.message,stderr};}
 process.stdout.write(JSON.stringify(result)+'\n');process.exitCode=result.status==='pass'?0:1;
})();
