/* LAB-MOTES-001: independent prices/work/reward chronology on production code. */
window.labMotesSeed=function(b,ctx){return window.inquirySeed(b,ctx);};
window.runLabMotesQa=function(b,ctx,assert,protectedParity,summaryParity){
  var checks=0,t=b.labMotes,clock=2000000000000,records=[];
  function ok(v,m){checks++;assert(v,'LAB oracle: '+m);}
  function same(a,c,m){ok(JSON.stringify(a)===JSON.stringify(c),m);}
  function near(a,c,m){ok(Math.abs(a-c)<1e-7,m+' ('+a+' vs '+c+')');}
  function seed(){return window.labMotesSeed(b,ctx);}
  function install(s){b.setState(s);b.renderLayout();}
  function active(id){return b.getState().activeStudies.find(function(a){return a.id===id;});}
  function paid(s,id,remaining,speed){s.activeStudies.push({id:id,remainingSec:remaining,totalDurationSec:Math.max(remaining,180),speedMult:speed||1});s.studyUseMotes[id]=true;s.studySpeedTargets[id]=3;return s;}
  function negative(kind,fn){var undo=t.mutate(kind),caught=false;try{fn();}catch(e){caught=/LAB oracle/.test(e.message);}finally{undo();}ok(caught,'causal mutant caught '+kind);fn();}
  b.resetFeedback();
  if(ctx.scenario==='lab-motes-contracts'){
    var tiers=[1.5,2,3,4,5,6,7,8],prices=[14,26,60,110,176,258,357,473];
    tiers.forEach(function(speed,i){
      var s=paid(seed(),'guardmastery',150);s.studySpeedTargets.guardmastery=speed;s.motes=prices[i];install(s);
      var r=t.direct(1);ok(r.summary.studySpeedPurchases===1&&r.summary.studyMotesSpent===prices[i]&&r.state.motes===0,'full existing tier price '+speed);
      near(active('guardmastery').remainingSec,150-speed,'no retroactive work '+speed);ok(active('guardmastery').speedMult===speed,'exact target '+speed);
    });
    function waiting(){var s=paid(seed(),'guardmastery',150);s.motes=59;install(s);var r=t.direct(1);ok(r.state.motes===59&&active('guardmastery').speedMult===1&&r.summary.studySpeedPurchases===0,'59 waits for exact3x without cheaper fallback');near(active('guardmastery').remainingSec,149,'waiting1x work');ok(r.state.studyUseMotes.guardmastery&&r.state.studySpeedTargets.guardmastery===3,'waiting intent retained');}
    waiting();negative('fallback',waiting);
    [false,true].forEach(function(queue){[false,true].forEach(function(use){var s=seed();s.motes=60;s.studyQueue.guardmastery=queue;s.studyUseMotes.guardmastery=use;s.studySpeedTargets.guardmastery=3;install(s);var r=t.direct(0);ok(!!active('guardmastery')===queue,'Queue alone starts '+queue+'/'+use);ok(r.summary.studySpeedPurchases===(queue&&use?1:0),'independent use '+queue+'/'+use);if(!queue){ok(b.inquiry.start('guardmastery'),'manual start allowed');r=t.direct(0);ok(active('guardmastery').speedMult===(use?3:1),'manual start respects independent use');}});});
    function repeat(){var s=seed();s.motes=120;s.studyQueue.guardmastery=true;s.studyUseMotes.guardmastery=true;s.studySpeedTargets.guardmastery=3;install(s);var r=b.inquiry.tail(50);ok(r.state.longStudyLevels.guardmastery===1&&active('guardmastery').speedMult===3&&r.state.motes===0,'new level pays60 again, never free carry');ok(r.summary.studyMotesSpent===120&&r.summary.studySpeedPurchases===2,'two full debits');near(active('guardmastery').remainingSec,240,'new level has no prepaid work');}
    repeat();negative('free-carry',repeat);
    var s=seed();s.motes=60;s.studyQueue.guardmastery=true;s.studyUseMotes.guardmastery=true;s.studySpeedTargets.guardmastery=3;install(s);var r=b.inquiry.tail(51);ok(active('guardmastery').speedMult===1&&r.state.motes===0,'new level waits1x when second price absent');near(active('guardmastery').remainingSec,239,'new level only actual1x elapsed');
    s=paid(seed(),'guardmastery',150,4);s.motes=60;install(s);r=t.direct(1);ok(active('guardmastery').speedMult===4&&r.state.motes===60,'higher paid speed skips debit and downgrade');
    s=paid(seed(),'guardmastery',150,3);s.studyUseMotes.guardmastery=false;install(s);r=t.direct(1);ok(active('guardmastery').speedMult===3&&r.summary.studySpeedPurchases===0,'OFF keeps paid speed');
    s=paid(seed(),'guardmastery',150);s.studyUseMotes.guardmastery=false;s.motes=60;install(s);ok(t.manual('guardmastery',3),'successful manual buy');ok(b.getState().studySpeedTargets.guardmastery===3&&!b.getState().studyUseMotes.guardmastery,'manual remembers target without enabling');ok(!t.manual('guardmastery',3)&&b.getState().motes===0,'manual no double buy');
    [0,1.25,9,'3',NaN].forEach(function(speed){ok(!t.manual('guardmastery',speed),'invalid manual tier rejected');});ok(!t.manual('unknown',8),'unknown manual ID');
    s=paid(seed(),'guardmastery',150,3);s.motes=109;s.studySpeedTargets.guardmastery=4;install(s);r=t.direct(0);ok(active('guardmastery').speedMult===3&&r.state.motes===109,'higher target waits at current paid3x');s=b.getState();s.motes=110;install(s);r=t.direct(0);ok(active('guardmastery').speedMult===4&&r.state.motes===0&&r.summary.studyMotesSpent===110,'higher target pays full price, no delta discount');near(active('guardmastery').remainingSec,150,'time-zero upgrade never creates work');
    s=paid(seed(),'guardmastery',150);s.studyUseMotes.guardmastery=false;s.motes=60;install(s);r=t.direct(0);ok(r.state.motes===60&&active('guardmastery').speedMult===1,'OFF stops affordable pending purchase');
    s=paid(seed(),'guardmastery',150);s.motes=60;var canonical=b.forge.canonical(s);ok(canonical.motes===60&&canonical.activeStudies[0].speedMult===1&&canonical.studyUseMotes.guardmastery,'valid ON normalization retains intent without spending');
    [false,true].forEach(function(reverse){s=paid(paid(seed(),'guardmastery',10),'wispascend',100);s.motes=60;if(reverse)s.activeStudies.reverse();install(s);r=t.direct(0);ok(active('wispascend').speedMult===3&&active('guardmastery').speedMult===1&&r.state.motes===0,'catalogue priority despite soonest/UI/active order '+reverse);});
    s=seed();delete s.studyUseMotes;delete s.studySpeedTargets;s.activeStudies=[{id:'guardmastery',remainingSec:70,totalDurationSec:150,speedMult:4}];var before=JSON.stringify(s),n=b.forge.canonical(s);ok(n.studySpeedTargets.guardmastery===4&&!n.studyUseMotes.guardmastery,'old save paid default4x/OFF');same(s,JSON.parse(before),'normalization input purity');same(b.forge.canonical(n),n,'normalization idempotent');ok(n.motes===s.motes,'normalization never buys');
    s=seed();s.studyUseMotes={unknown:true,guardmastery:'true',wispascend:true,riftattune:true};s.studySpeedTargets={unknown:8,guardmastery:3,wispascend:'3',riftattune:9};n=b.forge.canonical(s);ok(!n.studyUseMotes.guardmastery&&!n.studyUseMotes.wispascend&&!n.studyUseMotes.riftattune,'strict booleans and malformed targets cannot enable');same(Object.keys(n.studyUseMotes),b.inquiry.nodes().map(function(x){return x.id;}),'known saved IDs only');
    [10,13].forEach(function(level){s=paid(seed(),'measuredinquiry',1);s.longStudyLevels.measuredinquiry=level;s.studyQueue.measuredinquiry=true;s.motes=60;install(s);r=b.inquiry.tail(2);ok(r.state.motes===60&&r.summary.studySpeedPurchases===0&&r.state.longStudyLevels.measuredinquiry===level&&!r.state.activeStudies.length,'capped/overcap closure never spends '+level);});
    s=paid(seed(),'guardmastery',0);s.motes=60;install(s);r=t.direct(0);ok(r.state.motes===60&&r.summary.studySpeedPurchases===0&&!active('guardmastery'),'due closed record never spends');
    s=paid(seed(),'motestudy',100);s.maxDepthEver=59;s.depth=s.enemyDepth=59;s.enemyHp=s.enemyMaxHp=b.enemyHpFor(59);install(s);r=t.direct(0);ok(r.summary.studySpeedPurchases===0,'locked active cannot spend');
    return {checks:checks,negativeControls:['fallback','free-carry'],tiers:tiers,prices:prices,normalizationPure:true};
  }
  if(ctx.scenario==='lab-motes-chronology'){
    function farm(options){var s=seed();s.depth=s.enemyDepth=s.farmDepth=11;s.farmReturnDepth=12;s.riftMode='farm';s.enemyMaxHp=b.enemyHpFor(11);s.enemyHp=s.enemyMaxHp*.5;s.luminousAccum=.95;s.enemyIsLuminous=false;s.motes=58;delete s.achieved.autotap;paid(s,'guardmastery',150);Object.assign(s,options||{});return s;}
    function run(s,seconds,kind,chunk){install(s);return t.withDps(s.enemyMaxHp*100,function(){return chunk?b.simulate(seconds,kind,chunk,clock):t.direct(seconds,kind,clock);});}
    function boundary(){var s=farm(),r=run(s,.1,'offline'),events=r.summary.timeline.filter(function(e){return e.type==='studySpeed';});ok(events.length===1&&events[0].detail.cost===60&&events[0].detail.speed===3,'one direct60 purchase at luminous boundary');near(events[0].elapsedSec,.015,'actual second kill, including partial HP');near(active('guardmastery').remainingSec,150-.015-(.1-.015)*3,'elapsed work changes only after reward');ok(r.state.motes===0&&r.summary.luminousKills===1&&r.summary.kills===10,'actual deterministic reward/balance, not expected chance');records.push({case:'second-kill',summary:r.summary,active:r.state.activeStudies,motes:r.state.motes});}
    boundary();negative('batch-end',boundary);
    [.014999,.015,.015001].forEach(function(seconds){var r=run(farm(),seconds,'live');ok(active('guardmastery').speedMult===(seconds<.015?1:3),'before/exact/after actual reward '+seconds);ok(r.summary.studySpeedPurchases===(seconds<.015?0:1),'exact purchase count '+seconds);});
    [false,true].forEach(function(first){[.01,.37,.95].forEach(function(accum){[1,2,5].forEach(function(rewards){var s=farm({enemyIsLuminous:first,luminousAccum:accum,motes:60-2*rewards}),kills=0,luminous=0,a=accum,flag=first;while(luminous<rewards){kills++;if(flag)luminous++;a+=.05;flag=a>=1-1e-12;if(flag)a-=1;}var time=(kills-.5)/100,r=run(s,time+.001,'offline');var event=r.summary.timeline.find(function(e){return e.type==='studySpeed';});ok(!!event,'pending target eventually paid');near(event.elapsedSec,time,'independent spawn-by-spawn oracle '+first+'/'+accum+'/'+rewards);near(active('guardmastery').remainingSec,150-time-.003,'work oracle after nth luminous');records.push({case:[first,accum,rewards],kill:kills,time:time,purchase:event,motes:r.state.motes});});});});
    [0,10].forEach(function(tracking){var s=farm({luminousAccum:.37,motes:56});s.research.luminoustracking=tracking;s.longStudyLevels.motestudy=5;var chance=.05+.005*tracking,a=.37,flag=false,kills=0;while(!flag){kills++;a+=chance;if(a>=1-1e-12){flag=true;a-=1;}}kills++;var time=(kills-.5)/100,r=run(s,time+.001,'offline'),event=r.summary.timeline.find(function(e){return e.type==='studySpeed';});near(event.elapsedSec,time,'actual changed chance '+chance+' and rounded4-Mote reward');ok(r.summary.motesGained===4&&r.state.motes===0,'Long Study Mote reward remains unscaled');records.push({case:'tracking-reward',tracking:tracking,time:time,summary:r.summary});});
    var supported=farm({motes:55});supported.longStudyLevels.motestudy=5;supported.activeParty=['ember','tide'];supported.spirits.tide=1;supported.wispModules.tide=4;var boosted=run(supported,.02,'offline');ok(boosted.summary.motesGained===5&&boosted.state.motes===0,'actual rounded support-module reward5, no expected rate');near(boosted.summary.timeline.find(function(e){return e.type==='studySpeed';}).elapsedSec,.015,'support reward boundary');
    var base=farm(),one=run(base,.75,'live'),split=run(base,.75,'live',.025),offline=run(base,.75,'offline');protectedParity(split.state,one.state,'Motes split/live');summaryParity(split.summary,one.summary,'Motes split/live');same(split.state.studySpeedTargets,one.state.studySpeedTargets,'target parity');same(split.state.studyUseMotes,one.state.studyUseMotes,'intent parity');same([offline.state.motes,offline.state.activeStudies],[one.state.motes,one.state.activeStudies],'Motes work/live/offline parity');var offSplit=run(base,.75,'offline',.025);protectedParity(offSplit.state,offline.state,'Motes offline split');summaryParity(offSplit.summary,offline.summary,'Motes offline split');['motesGained','luminousKills','studySpeedPurchases','studyMotesSpent'].forEach(function(k){ok(offline.summary[k]===one.summary[k],'unscaled Motes policy '+k);});near(offline.summary.lumenGained,one.summary.lumenGained*.7,'existing offline Lumen rate');near(offline.summary.shardGained,one.summary.shardGained*.7,'existing offline Shard rate');
    var small=run(farm({motes:60-1e-12,enemyIsLuminous:true}),.005,'offline');ok(small.summary.studySpeedPurchases===1&&small.summary.kills===1,'tiny positive deficit waits real reward without zero-time loop');
    var multi=farm({motes:118,enemyIsLuminous:true});paid(multi,'wispascend',100);var r=run(multi,.1,'live'),events=r.summary.timeline.filter(function(e){return e.type==='studySpeed';});same(events.map(function(e){return e.detail.id;}),['wispascend','guardmastery'],'shared budget declaration order');near(events[0].elapsedSec,0,'first target already affordable at entry');near(events[1].elapsedSec,.005,'second shared budget purchase');ok(r.state.motes===2,'multiple prices only actual rewards');
    var collision=farm();collision.activeStudies[0].remainingSec=.015;collision.studyQueue.guardmastery=true;collision.longStudyLevels.measuredinquiry=9;paid(collision,'measuredinquiry',.015);collision.buffUntil=clock+15;collision.buffMult=2;
    r=run(collision,.02,'offline');ok(r.state.longStudyLevels.measuredinquiry===10&&r.summary.studyMotesSpent===60&&r.summary.studySpeedPurchases===1,'reward/completion/start/cap/buff collision buys only eligible new level');ok(active('guardmastery').speedMult===3&&!active('measuredinquiry'),'cap closes before purchase');near(active('guardmastery').remainingSec,192-.005*3,'Inquiry10 discount on new snapshot without retroactive work');var types=r.summary.timeline.filter(function(e){return Math.abs(e.elapsedSec-.015)<1e-8;}).map(function(e){return e.type;});ok(types.indexOf('buffExpire')<types.indexOf('studyComplete')&&types.indexOf('studyComplete')<types.indexOf('studyStart')&&types.indexOf('studyStart')<types.indexOf('studySpeed'),'timestamp order buff/completion/start/speed');records.push({case:'collision',summary:r.summary,state:r.state});
    var push=paid(seed(),'guardmastery',150);push.motes=58;push.enemyHp=push.enemyMaxHp*.5;push.enemyIsLuminous=true;install(push);r=t.withDps(push.enemyMaxHp*100,function(){return t.direct(.01,'live');});near(r.summary.timeline.find(function(e){return e.type==='studySpeed';}).elapsedSec,.005,'push actual reward boundary');
    var ascend=paid(seed(),'guardmastery',150);ascend.depth=ascend.enemyDepth=17;ascend.enemyMaxHp=b.enemyHpFor(17);ascend.enemyHp=ascend.enemyMaxHp;ascend.owned.autoascend=true;ascend.autoAscendEnabled=true;ascend.autoAscendTargetDepth=16;ascend.motes=60;install(ascend);r=t.direct(0);ok(r.summary.ascends===1&&r.summary.studySpeedPurchases===1&&r.state.studyUseMotes.guardmastery&&active('guardmastery').speedMult===3,'time-zero Ascend retains intent then eligible speed');
    var killed=paid(seed(),'guardmastery',.005);killed.depth=killed.enemyDepth=16;killed.enemyMaxHp=b.enemyHpFor(16);killed.enemyHp=killed.enemyMaxHp*.5;killed.enemyIsLuminous=true;killed.motes=58;killed.studyQueue.guardmastery=true;killed.owned.autoascend=true;killed.autoAscendEnabled=true;killed.autoAscendTargetDepth=17;install(killed);r=t.withDps(killed.enemyMaxHp*100,function(){return t.direct(.005,'live');});ok(r.summary.ascends===1&&r.summary.completedStudies.length===1&&r.summary.studySpeedPurchases===0&&!r.state.activeStudies.length,'same kill reward/Ascend/completion respects reset start budget and closed record');ok(r.state.motes===61&&r.state.studyUseMotes.guardmastery&&r.state.studySpeedTargets.guardmastery===3,'collision retains unspent actual3-Mote reward and intent');records.push({case:'kill-ascend-complete',summary:r.summary,motes:r.state.motes});
    var tail=seed();tail.motes=60;tail.lumen=tail.shards=0;paid(tail,'guardmastery',129603);install(tail);b.setLastSeen(b.clockNow()-43203*1000);r=b.applyOfflineProductiveOnly();ok(r.effectiveSec===43200&&r.studySpeedPurchases===1&&b.getState().longStudyLevels.guardmastery===0,'paid speed shares exactly 12h; no productive tail');near(b.getState().activeStudies[0].remainingSec,3,'remaining paid work at12h');
    tail=seed();tail.motes=60;tail.lumen=tail.shards=0;paid(tail,'guardmastery',9);install(tail);r=b.inquiry.tail(3);ok(r.summary.studySpeedPurchases===1&&r.state.longStudyLevels.guardmastery===1&&r.state.motes===0,'study-only tail same exact paid work');
    return {checks:checks,negativeControls:['batch-end'],timelineEvidence:records,liveOfflineSplit:true};
  }
  var q=function(s){return document.querySelector(s);},s=paid(seed(),'guardmastery',150);s.motes=0;s.studyUseMotes.guardmastery=false;install(s);q('[data-tab="research"]').click();
  var before=b.getState();b.renderLayout();same(b.getState(),before,'render cannot pay');
  q('[data-study-details="guardmastery"]').click();var select=q('[data-study-speed-target="guardmastery"]');select.focus();select.value='3';select.dispatchEvent(new Event('change',{bubbles:true}));ok(document.activeElement.dataset.studySpeedTarget==='guardmastery','select focus survives target change');ok(b.getState().studySpeedTargets.guardmastery===3&&b.getState().motes===0,'target selectable without money');
  var button=q('[data-study-use-motes="guardmastery"]');button.focus();button.click();ok(document.activeElement.dataset.studyUseMotes==='guardmastery','toggle focus survives');ok(q('[data-study-use-motes="guardmastery"]').getAttribute('aria-pressed')==='true'&&!b.getState().studyQueue.guardmastery,'Use Motes aria ON independent of queue');
  var snapshot=b.getState(),save=b.rawSave(),recovery=b.rawRecovery(),events=b.lifecycleTrace();b.renderLayout();same(b.getState(),snapshot,'render state purity');same([b.rawSave(),b.rawRecovery(),b.lifecycleTrace()],[save,recovery,events],'render save/observer purity');
  var buy=q('[data-speed-study="guardmastery"][data-speed="3"]');ok(buy.disabled&&buy.textContent.includes('60')&&!/Need|Cannot afford/.test(buy.textContent+' '+buy.getAttribute('aria-label')),'poor purchase keeps action/price quietly');
  document.querySelectorAll('#study-list details').forEach(function(panel){panel.open=true;});var controls=Array.from(q('#study-list').querySelectorAll('[data-study-use-motes],[data-study-speed-target]'));controls.forEach(function(e){var rect=e.getBoundingClientRect();ok(e.offsetHeight>=44&&e.offsetWidth>=44,'44px native controls');ok(!!e.getAttribute('aria-label'),'accessible study subject/action');});
  ok(document.documentElement.scrollWidth<=innerWidth+1&&q('#study-list').scrollWidth<=q('#study-list').clientWidth+1,'no horizontal overflow');same(Array.from(document.querySelectorAll('nav.tabbar .tab-btn')).map(function(e){return e.dataset.tab;}),['spirits','workshop','battle','ascend','deeds'],'NAV ordered five destinations');q('[data-tab="battle"]').click();ok(q('main').scrollHeight<=q('main').clientHeight+1,'Rift remains scroll-free');
  return {checks:checks,viewport:[innerWidth,innerHeight],focus:true,ariaPressed:true,quietScarcity:true,nativeControls:true};
};
window.runLabMotesPersistence=function(b,ctx,assert,phase,nextPhase,backupCode,finish){
  var keys=['schemaVersion','studyQueue','studyUseMotes','studySpeedTargets','activeStudies','motes'];
  if(phase()===0){var s=window.labMotesSeed(b,ctx);s.studyUseMotes.guardmastery=true;s.studySpeedTargets.guardmastery=3;s.studySpeedTargets.wispascend=8;s.studyQueue.wispascend=true;s.motes=0;s.activeStudies=[{id:'guardmastery',remainingSec:77,totalDurationSec:150,speedMult:4}];b.setState(s);b.feedbackSave();var expected=b.getState();localStorage.setItem('lab-motes-expected',JSON.stringify(expected));nextPhase(1);if(ctx.scenario==='lab-motes-reset'){b.reset();return;}if(ctx.scenario==='lab-motes-backup-restore'){b.setState(b.freshStateSnapshot());b.restoreBackup(backupCode(expected));return;}if(ctx.scenario==='lab-motes-recovery')b.formationTest.corruptPrimary();b.suppressUnloadSave();location.reload();return;}
  var s=b.getState(),expected=JSON.parse(localStorage.getItem('lab-motes-expected'));
  if(ctx.scenario==='lab-motes-reset'){assert(s.schemaVersion===1&&!s.activeStudies.length&&Object.values(s.studyUseMotes).every(function(v){return v===false;})&&Object.values(s.studySpeedTargets).every(function(v){return v===1.5;}),'actual Reset clears intent, targets and work');finish('pass',{reset:true});return;}
  keys.forEach(function(key){assert(JSON.stringify(s[key])===JSON.stringify(expected[key]),ctx.scenario+' preserves '+key);});
  ['studyUseMotes','studySpeedTargets','activeStudies'].forEach(function(key){assert(JSON.stringify(JSON.parse(b.rawRecovery())[key])===JSON.stringify(expected[key]),'recovery retains '+key);});
  s.depth=s.enemyDepth=16;s.enemyMaxHp=s.enemyHp=b.enemyHpFor(16);b.setState(s);b.ascendManual();s=b.getState();['studyUseMotes','studySpeedTargets','activeStudies','studyQueue'].forEach(function(key){assert(JSON.stringify(s[key])===JSON.stringify(expected[key]),'Ascend preserves '+key);});finish('pass',{keys:keys,ascend:true,activeSpeed:4,independentTarget:3});
};
